version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: auth-postgres

    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: auth-redis

    ports:
      - "6380:6379"

  prometheus:
    image: prom/prometheus
    container_name: auth-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: auth-grafana

    ports:
      - "3000:3000"

volumes:
  postgres_data: