global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "auth-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-api:8081"]
rule_files:
  - "/infra/alerts.yml"
