server:
  port: 8080

spring:
  application:
    name: auth-api

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: authuser
    password: authpass

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  data:
    redis:
      host: localhost
      port: 6380

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh-expiration: 604800000